#!/bin/bash

TGF_FILE=$1

if [[ -z "$TGF_FILE" ]]; then
	echo "provide an existing TGF file path"
	exit 1
fi

TGF_DIR="./external/parser"
TGF="$TGF_DIR/build-Release/tgf"

if [[ ! -f "$TGF" ]]; then
	echo "tgf tool not built. Building..."
	D=`pwd`
	cd "$TGF_DIR"
	./dev release -DTAU_PARSER_BUILD_TGF=1
	cd "$D"
fi

echo "Generating parser from $TGF_FILE ..."
$TGF "$TGF_FILE" gen
echo "Generation done"
