#!/bin/bash

# Parsers are generated by the build itself, from the grammars core and each BA
# in the pack declare, into <build>/generated/. Nothing is committed, so there
# is nothing to regenerate by hand: this only builds the generation target of a
# build directory, which is what a grammar edit needs.
#
# Usage: ./dev regen [build-dir]   (default build/devel)

set -euo pipefail

root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
build="${1:-$root/build/devel}"

if [ ! -d "$build" ]; then
	echo "No such build directory: $build" >&2
	echo "Configure one first, e.g. ./dev preset devel" >&2
	exit 1
fi

cmake --build "$build" --target tau_parsers
