// To view the license please visit https://github.com/IDNI/tau-lang/blob/main/LICENSE.md

#ifndef __IDNI__TAU__TAU_COMPILE_TMPL_H__
#define __IDNI__TAU__TAU_COMPILE_TMPL_H__

#include <cstdlib>
#include <exception>
#include <filesystem>
#include <fstream>
#include <map>
#include <optional>
#include <sstream>

#include "cpp_codegen.h"
#include "definitions.h"
#include "tau_pack.h"
#include "utility/escapes.h"

namespace idni::tau_lang {

namespace compile_detail {

// RAII: clears definitions<Node>'s process-wide rule table, I/O context and
// type scope for the guard's lifetime and restores the prior state on
// destruction, so a compile starts from and leaves behind a clean type scope.
template <NodeType Node>
struct scoped_clean_definitions {
	scoped_clean_definitions()
		: defs(definitions<Node>::instance()), saved(defs.save()) {
		defs.clear();
	}
	~scoped_clean_definitions() { defs.restore(std::move(saved)); }
	scoped_clean_definitions(const scoped_clean_definitions&) = delete;
	scoped_clean_definitions& operator=(const scoped_clean_definitions&) = delete;
private:
	definitions<Node>& defs;
	typename definitions<Node>::snapshot saved;
};

// True iff `cxx` answers `--version` successfully (probed, not hardcoded).
inline bool compiler_available(const std::string& cxx) {
	std::string cmd = cxx + " --version >/dev/null 2>&1";
	return std::system(cmd.c_str()) == 0;
}

// clang++ preferred: GCC 16 ICEs on heavy TUs in this environment; falls
// back to letting cmake pick its own default when clang++ is not found.
inline std::string preferred_cxx_flag() {
	return compiler_available("clang++") ? " -DCMAKE_CXX_COMPILER=clang++" : "";
}

// CMakeLists for the emitted artifact: links the emitting build's prebuilt libTAU.a and its BA libs, under tau-common.cmake's own policy.
inline std::string emit_cmake_sdk_linked(const std::string& exe_name) {
	std::ostringstream os;
	os <<
		"# Generated by `tau compile`. DO NOT EDIT.\n"
		"cmake_minimum_required(VERSION 3.22.1 FATAL_ERROR)\n"
		"project(tau_compiled_spec CXX)\n"
		"\n"
		"# Baked paths from the tau binary that emitted this project.\n"
		"set(TAU_SDK_ROOT \"" << TAU_CODEGEN_SDK_ROOT << "\")\n"
		"set(TAU_SDK_BUILD_DIR \"" << TAU_CODEGEN_BUILD_DIR << "\")\n"
		"set(TAU_SDK_SHARED_PREFIX \"" << TAU_CODEGEN_SHARED_PREFIX << "\")\n"
		"set(TAU_BA_LINK_LIBS \"" << TAU_CODEGEN_BA_LINK_LIBS << "\")\n"
		"set(TAU_COMPILE_DEFINITIONS \"" << TAU_CODEGEN_COMPILE_DEFINITIONS << "\")\n"
		"\n"
		"list(APPEND CMAKE_MODULE_PATH \"${TAU_SDK_ROOT}/cmake\")\n"
		"\n"
		"# tau-common.cmake's LTO gate keys off this toggle; this project never\n"
		"# includes the top-level CMakeLists.txt that normally sets it. The\n"
		"# artifact is one small TU linking a prebuilt libTAU.a, so LTO across\n"
		"# that library buys nothing and only slows the link; keep it off here.\n"
		"set(TAU_BUILD_EXECUTABLE OFF)\n"
		"include(\"${TAU_SDK_ROOT}/cmake/tau-common.cmake\")\n"
		"\n"
		"# Resolve the packages TAU_BA_LINK_LIBS' imported targets need, the\n"
		"# same way the emitting build's own CMakeLists.txt does.\n"
		"foreach(_tau_ba_lnk ${TAU_BA_LINK_LIBS})\n"
		"\tif(_tau_ba_lnk MATCHES \"^([A-Za-z0-9_]+)::.+$\")\n"
		"\t\tset(_tau_ba_lnk_pkg \"${CMAKE_MATCH_1}\")\n"
		"\t\tif(NOT TARGET \"${_tau_ba_lnk}\")\n"
		"\t\t\tfind_package(${_tau_ba_lnk_pkg} QUIET PATHS\n"
		"\t\t\t\t\"${TAU_SDK_SHARED_PREFIX}/${_tau_ba_lnk_pkg}/dist/lib/cmake/${_tau_ba_lnk_pkg}\")\n"
		"\t\t\tif(NOT ${_tau_ba_lnk_pkg}_FOUND)\n"
		"\t\t\t\tfind_package(${_tau_ba_lnk_pkg} REQUIRED)\n"
		"\t\t\tendif()\n"
		"\t\tendif()\n"
		"\tendif()\n"
		"endforeach()\n"
		"\n"
		"# Boost: the same custom build the emitting tau binary linked.\n"
		"set(Boost_USE_STATIC_LIBS ON)\n"
		"file(GLOB _tau_boost_cfg\n"
		"\t\"${TAU_SDK_SHARED_PREFIX}/boost/dist/lib/cmake/Boost-*/BoostConfig.cmake\")\n"
		"if(_tau_boost_cfg)\n"
		"\tlist(GET _tau_boost_cfg 0 _tau_boost_cfg_first)\n"
		"\tget_filename_component(Boost_DIR \"${_tau_boost_cfg_first}\" DIRECTORY)\n"
		"endif()\n"
		"find_package(Boost REQUIRED COMPONENTS log)\n"
		"\n"
		"# tauparser and the pack's static library: prebuilt by the emitting\n"
		"# build, reused rather than recompiled for this one small TU.\n"
		"add_library(tau_prebuilt_parser STATIC IMPORTED)\n"
		"set_target_properties(tau_prebuilt_parser PROPERTIES\n"
		"\tIMPORTED_LOCATION \"${TAU_SDK_BUILD_DIR}/libtauparser.a\"\n"
		"\tINTERFACE_INCLUDE_DIRECTORIES \"${TAU_SDK_ROOT}/external/parser/src\")\n"
		"add_library(tau_prebuilt STATIC IMPORTED)\n"
		"set_target_properties(tau_prebuilt PROPERTIES\n"
		"\tIMPORTED_LOCATION \"${TAU_SDK_BUILD_DIR}/libTAU.a\")\n"
		"\n"
		"add_executable(" << exe_name << " main.cpp)\n"
		"target_include_directories(" << exe_name << " PRIVATE\n"
		"\t\"${TAU_SDK_BUILD_DIR}/generated/include\"\n"
		"\t\"${TAU_SDK_BUILD_DIR}/generated/parser\"\n"
		"\t\"${TAU_SDK_ROOT}/src\"\n"
		"\t\"${TAU_SDK_ROOT}/parser\"\n"
		"\t\"${TAU_SDK_ROOT}/external/parser/src\"\n"
		"\t\"${TAU_SDK_ROOT}/external/cvc5/include\"\n"
		"\t\"${TAU_SDK_ROOT}/external/cvc5/build/include\")\n"
		"target_include_directories(" << exe_name << " SYSTEM PRIVATE\n"
		"\t\"${TAU_SDK_BUILD_DIR}/_deps/unordered_dense-src/include\")\n"
		"target_setup(" << exe_name << ")\n"
#ifdef DEBUG
		// The prebuilt libraries carry DEBUG, so the artifact must too.
		"target_compile_options(" << exe_name << " PRIVATE -UNDEBUG -DDEBUG)\n"
#endif
		"target_link_libraries(" << exe_name << " PRIVATE\n"
		"\ttau_prebuilt tau_prebuilt_parser Boost::log ${TAU_BA_LINK_LIBS})\n"
		"\n"
		"# Matches the emitting build's ABI-affecting toggles (e.g.\n"
		"# TAU_PARSER_MEASURE*) so this TU's header-only template instantiations\n"
		"# share libTAU.a/libtauparser.a's layout; kept last so nothing above can\n"
		"# undo it.\n"
		"target_compile_definitions(" << exe_name <<
			" PRIVATE ${TAU_COMPILE_DEFINITIONS})\n";
	return os.str();
}

// The artifact's one main: replays the baked ba-type table, rebuilds
// atoms/strategy/templates/witnesses from the desc, and drives the same
// run_loop() the tau binary's own `run` uses. Whether a witness is a baked
// constant (edge_witnesses) or solved per step (edge_witness_templates) is a
// table_step_provider construction detail, not a different main.
inline void emit_main(const program_desc& d, std::ostream& f) {
	f <<
		"// Auto-generated driver for a tau-compiled spec.\n"
		"// tau.h first: the amalgamation orders solver/interpreter internals\n"
		"// that piecemeal includes cannot.\n"
		"#include \"tau.h\"\n"
		"#include \"tau_pack.h\"\n"
		"#include \"table_step_provider.h\"\n"
		"#include \"cli_options.h\"\n"
		"#include <chrono>\n"
		"#include <cstdio>\n"
		"#include <cstdlib>\n"
		"#include <cstring>\n"
		"#include <iostream>\n"
		"#include <map>\n"
		"#include <memory>\n"
		"#include <string>\n"
		"#include <utility>\n"
		"#include <vector>\n"
#ifdef TAU_CODEGEN_ARTIFACT_PREINST
		"#include \"artifact_pack_extern.h\"\n"
#endif
		"using namespace std;\n"
		"using namespace idni::tau_lang;\n"
		"using node_t = tau_pack::node_t;\n"
		"using tref = ::idni::tref;\n"
		"\n"
		"static const char* spec_src() {\n"
		"\treturn \"" << idni::escapes::encode(d.spec_src,
			idni::escapes::c_like) << "\";\n"
		"}\n"
		"\n"
		"int main(int argc, char** argv) {\n"
		"\tif (argc > 1 && strcmp(argv[1], \"--print-spec\") == 0) {\n"
		"\t\tputs(spec_src());\n"
		"\t\treturn 0;\n"
		"\t}\n"
		"\tvector<string> args;\n"
		"\tfor (int i = 0; i < argc; ++i) args.push_back(argv[i]);\n"
		"\tidni::cli cl(\"program\", args, idni::cli::commands{}, \"\",\n"
		"\t\ttau_cli_options(cli_option_set::artifact));\n"
		"\tcl.set_help_header(\"Usage: program [<options>]\");\n"
		"\tif (cl.process_args() != 0) return cl.status();\n"
		"\tauto opts = cl.get_processed_options();\n"
		"\tif (opts[\"help\"].get<bool>()) return cl.help(), 0;\n"
		"\tif (opts[\"version\"].get<bool>())\n"
		"\t\treturn cout << full_version << \"\\n\", 0;\n"
		"\tif (opts[\"license\"].get<bool>()) return cout << license, 0;\n"
		"\tlogging::set_filter(\n"
		"\t\ttau_cli_parse_severity(opts[\"severity\"].get<string>()));\n"
		"\tprint_json = opts[\"json\"].get<bool>();\n"
		"\tbool quit_on_idle = opts[\"quit\"].get<bool>();\n"
		"\tbool print_benchmarks = opts[\"benchmarks\"].get<bool>();\n"
		"\ttau_init<node_t>();\n"
		"\t// Replay the emitting process's ba-type registry so every baked\n"
		"\t// numeric type id resolves to the same type here; entries the\n"
		"\t// artifact's own static init already registered assert by identity.\n";
	for (auto& e : d.ba_type_table) {
		f << "\t{\n\t\ttref tt = ";
		switch (e.kind) {
		case ba_type_entry::recipe::reserved:
			f << e.name << "_type<node_t>()";
			break;
		case ba_type_entry::recipe::family:
			f << "pack_type_tree<node_t>(\"" << e.name << "\"";
			if (e.param) f << ", (unsigned short)" << *e.param;
			f << ")";
			break;
		case ba_type_entry::recipe::syntactic:
			f << "ba_types_detail::make_syntactic_type_tree"
			     "<node_t>(\"" << e.name << "\")";
			break;
		}
		f << ";\n"
		  << "\t\tif (!tt || ba_types<node_t>::id(tt) != " << e.id
		  << ") {\n"
		  << "\t\t\tfprintf(stderr, \"ba-type replay mismatch for "
		  << e.name;
		if (e.param) f << "[" << (int)*e.param << "]";
		f << " (expected id " << e.id << ")\\n\");\n"
		     "\t\t\treturn 2;\n\t\t}\n\t}\n";
	}
	f << "\n\tmap<string, tref> atoms;\n";
	for (auto& a : d.atoms)
		f << "\tatoms[\"" << a.prop << "\"] = " << a.ground_expr << ";\n";
	f << "\n\tcodegen::strategy strat;\n"
	  << "\tstrat.num_states = " << d.num_states << ";\n"
	  << "\tstrat.initial_state = " << d.initial_state << ";\n"
	  << "\tstrat.num_inputs = " << d.inputs.size() << ";\n"
	  << "\tstrat.edges.resize(" << d.num_states << ");\n"
	  << "\tvector<vector<vector<tref>>> templates("
	  << d.num_states << ");\n"
	  << "\tvector<vector<vector<bool>>> template_is_counter("
	  << d.num_states << ");\n"
	  << "\tvector<vector<vector<pair<string, tref>>>> "
	     "edge_witnesses(" << d.num_states << ");\n";
	// witness_ctors keys by the field's sanitized cpp_name; edge_witnesses
	// keys by the real output variable name (table_step_provider's own doc
	// comment, matching flag_outputs and the output streams) -- map one to
	// the other.
	std::map<std::string, std::string> witness_var_of_cpp_name;
	for (auto& fld : d.outputs)
		if (fld.kind == field_kind::witness)
			witness_var_of_cpp_name[fld.cpp_name] = fld.prop;
	for (int s = 0; s < d.num_states; ++s) {
		if ((size_t)s >= d.edges.size()) break;
		for (auto& e : d.edges[s]) {
			f << "\tstrat.edges[" << s << "].push_back({{";
			for (size_t k = 0; k < e.guard.size(); ++k)
				f << (k ? ", " : "") << (int)e.guard[k];
			f << "}, " << e.dst << "});\n";
			f << "\ttemplates[" << s << "].push_back({";
			for (size_t k = 0; k < e.witness_template_props.size(); ++k)
				f << (k ? ", " : "") << "atoms.at(\""
				  << e.witness_template_props[k] << "\")";
			f << "});\n";
			f << "\ttemplate_is_counter[" << s << "].push_back({";
			for (size_t k = 0; k < e.witness_template_is_counter.size(); ++k)
				f << (k ? ", " : "")
				  << (e.witness_template_is_counter[k] ? "true" : "false");
			f << "});\n";
			f << "\tedge_witnesses[" << s << "].push_back({";
			for (size_t k = 0; k < e.witness_ctors.size(); ++k) {
				const auto& [cpp_name, expr] = e.witness_ctors[k];
				f << (k ? ", " : "") << "{\""
				  << witness_var_of_cpp_name.at(cpp_name) << "\", " << expr
				  << "}";
			}
			f << "});\n";
		}
	}
	f << "\n\tvector<pair<string, tref>> input_atoms;\n";
	for (auto& fld : d.inputs)
		f << "\tinput_atoms.emplace_back(\"" << fld.prop
		  << "\", atoms.at(\"" << fld.prop << "\"));\n";
	f << "\tvector<string> flag_outputs;\n";
	for (auto& v : d.flag_output_vars)
		f << "\tflag_outputs.push_back(\"" << v << "\");\n";
	f << "\n\tio_context<node_t> ctx;\n";
	for (auto& s : d.input_streams) {
		if (s.bind == stream_desc::binding::file)
			f << "\tctx.add_input_file(\"" << s.name << "\", "
			  << s.ba_type << ", \""
			  << idni::escapes::encode(s.filename, idni::escapes::c_like)
			  << "\");\n";
		else
			f << "\tctx.add_input_console(\"" << s.name << "\", "
			  << s.ba_type << ");\n";
	}
	for (auto& s : d.output_streams) {
		if (s.bind == stream_desc::binding::file)
			f << "\tctx.add_output_file(\"" << s.name << "\", "
			  << s.ba_type << ", \""
			  << idni::escapes::encode(s.filename, idni::escapes::c_like)
			  << "\");\n";
		else
			f << "\tctx.add_output_console(\"" << s.name << "\", "
			  << s.ba_type << ");\n";
	}
	f <<
		"\n\tauto provider = make_shared<table_step_provider<node_t>>(\n"
		"\t\tstd::move(strat), std::move(input_atoms), std::move(flag_outputs),\n"
		"\t\tstd::move(edge_witnesses), std::move(templates), "
		"std::move(template_is_counter));\n"
		// Captured before the move below: step()'s input filter needs this
		// to tell which declared inputs a given step actually consults,
		// the same way the general solve path uses ubt_ctn.
		"\tvector<tref> live_probe_atoms = provider->live_probe_atoms();\n"
		"\tauto interp = interpreter<node_t>::make_table_interpreter(\n"
		"\t\tctx, std::move(provider), " << d.lookback << ", "
		<< d.highest_initial_pos << ", live_probe_atoms);\n"
		"\tif (!interp) {\n"
		"\t\tfprintf(stderr, \"interpreter initialization failed\\n\");\n"
		"\t\treturn 2;\n"
		"\t}\n"
		"\tauto run_start = std::chrono::steady_clock::now();\n"
		"\tbool run_ok = interp->run_loop(0, quit_on_idle);\n"
		"\tif (print_benchmarks)\n"
		"\t\tcerr << \"run: \" << std::chrono::duration<double, std::milli>(\n"
		"\t\t\tstd::chrono::steady_clock::now() - run_start).count()\n"
		"\t\t\t<< \" ms\\n\";\n"
		"\t// Flush and leave without running static destructors: the pack's\n"
		"\t// static state (caches, pools, the leaked cvc5 term manager) has no\n"
		"\t// safe cross-TU destruction order, and a buffered-stdout artifact\n"
		"\t// must not lose its written outputs to a teardown crash.\n"
		"\tcout.flush();\n"
		"\tfflush(nullptr);\n"
		"\t_Exit(run_ok ? 0 : 1);\n"
		"}\n";
}

} // namespace compile_detail

template <NodeType Node>
codegen_result compile_spec(
	const std::string& spec_src,
	const std::string& out_exe,
	const std::string& build_dir)
{
	namespace fs = std::filesystem;
	compile_detail::scoped_clean_definitions<Node> clean_defs;
	codegen_result res;

	fs::path bdir = build_dir.empty()
		? fs::current_path() / "spec.build"
		: fs::path(build_dir);
	std::error_code ec;
	fs::create_directories(bdir, ec);
	if (ec) {
		res.error = "compile: cannot create build dir " + bdir.string()
			+ ": " + ec.message();
		return res;
	}

	// 1. Parse the spec via get_spec -- the interpreter's own grammar
	// (trailing '.', stream/rec-relation definitions) -- through the same
	// nso_rr/normalizer pipeline get_interpreter uses.
	using tau_api = api<Node>;
	auto spec_res = tau_api::get_spec(spec_src);
	tref spec_tree = spec_res.has_value() ? spec_res.value() : nullptr;
	if (!spec_tree) {
		res.error = "compile: failed to parse spec";
		return res;
	}
	auto nso_rr = get_nso_rr<Node>(spec_tree);
	if (!nso_rr) {
		res.error = "compile: failed to build the recurrence relation from spec";
		return res;
	}
	auto applied_r = nso_rr_apply<Node>(*nso_rr);
	if (!applied_r.has_value()) {
		res.error = "compile: failed to apply the recurrence relation";
		return res;
	}
	tref applied = applied_r.value();
	auto normalized = normalizer<Node>(applied);
	if (!normalized.has_value()) {
		res.error = "compile: failed to normalize spec";
		return res;
	}
	tref fm = normalized.value();
	// fm is checked before solve_ltl_aba runs, so it is never a bare-reparsed atom.
	if (has_free_vars<Node>(fm)) {
		res.error = "compile: spec has unresolved free variables";
		return res;
	}

	// 2. Synthesize: solve_ltl_aba drives the same ABA/ltlsynt pipeline
	// the interpreter uses at runtime, but ahead of time. A positional
	// atom outside its supported scope surfaces here as a compile error,
	// not a crash.
	std::optional<ltl_aba_solution<Node>> sol;
	try {
		sol = solve_ltl_aba<Node>(fm);
	} catch (const std::exception& e) {
		res.error = std::string("compile: ") + e.what();
		return res;
	}
	if (!sol) {
		res.error = "compile: spec is UNREALIZABLE";
		return res;
	}

	// 3. Build the program_desc and emit the C++ artifact via the one
	// data-driven emit path (build_program_desc picks flag-only vs
	// witness-bearing itself; this wraps that choice rather than repeating
	// it). A synthesis-time refusal (PWR x witness, or a witness owner that
	// declines) surfaces here as a compile error, not a crash.
	const std::string class_name = "tau_program";
	std::optional<program_desc> d;
	try {
		d = build_program_desc<Node>(*sol, class_name, /*revisable=*/false,
			/*open_streams=*/{}, definitions<Node>::instance().get_io_context());
	} catch (const std::exception& e) {
		res.error = std::string("compile: ") + e.what();
		return res;
	}
	if (!d) {
		res.error = "compile: internal codegen error (no program_desc)";
		return res;
	}
	d->spec_src = spec_src;

	// Every flag output field must key its stream on a single variable --
	// emit_main's flag_outputs list has no other way to name its guard slot.
	for (size_t k = 0; k < d->flag_output_vars.size(); ++k)
		if (d->flag_output_vars[k].empty()) {
			res.error = "compile: flag output '"
				+ d->outputs[k].prop + "' has no single variable "
				"to key its stream on; the artifact cannot be emitted";
			return res;
		}

	// 4. Emit the one artifact main (main.cpp only -- see emit_main).
	{
		std::ofstream f(bdir / "main.cpp");
		if (!f) {
			res.error = "compile: cannot write main.cpp in " + bdir.string();
			return res;
		}
		compile_detail::emit_main(*d, f);
	}

	// 5. Emit CMakeLists.txt: every artifact links the emitting build's SDK.
	const std::string exe_name = "program";
	{
		std::ofstream f(bdir / "CMakeLists.txt");
		if (!f) {
			res.error = "compile: cannot write CMakeLists.txt in "
				+ bdir.string();
			return res;
		}
		f << compile_detail::emit_cmake_sdk_linked(exe_name);
	}

	// 6. Drive cmake configure + build.
	fs::path bin_dir = bdir / "build";
	std::string cxx_flag = compile_detail::preferred_cxx_flag();

	std::string config_log = (bdir / "configure.log").string();
	std::string config_cmd = "cmake -S \"" + bdir.string() + "\""
		+ " -B \"" + bin_dir.string() + "\""
		+ " -DCMAKE_BUILD_TYPE=Release" + cxx_flag
		+ " > \"" + config_log + "\" 2>&1";
	if (std::system(config_cmd.c_str()) != 0) {
		res.error = "compile: cmake configure failed, see " + config_log;
		return res;
	}

	std::string build_log = (bdir / "build.log").string();
	std::string build_cmd = "cmake --build \"" + bin_dir.string() + "\""
		+ " > \"" + build_log + "\" 2>&1";
	if (std::system(build_cmd.c_str()) != 0) {
		res.error = "compile: cmake build failed, see " + build_log;
		return res;
	}

	// 7. Locate the built executable (single- and multi-config layouts).
	fs::path built = bin_dir / exe_name;
	if (!fs::exists(built)) built = bin_dir / "Release" / exe_name;
	if (!fs::exists(built)) {
		res.error = "compile: built executable not found at "
			+ (bin_dir / exe_name).string();
		return res;
	}

	fs::path dest = out_exe.empty() ? (bdir / exe_name) : fs::path(out_exe);
	if (dest != built) {
		if (!dest.parent_path().empty())
			fs::create_directories(dest.parent_path(), ec);
		fs::copy_file(built, dest, fs::copy_options::overwrite_existing, ec);
		if (ec) {
			res.error = "compile: failed to copy executable to "
				+ dest.string() + ": " + ec.message();
			return res;
		}
	}
	res.exe_path = dest.string();
	return res;
}

} // namespace idni::tau_lang

#endif // __IDNI__TAU__TAU_COMPILE_TMPL_H__
