# populates TAU_GIT_DESCRIBED, TAU_GIT_BRANCH and TAU_GIT_COMMIT_HASH variables
# and creates TAU_GIT_DEFINITIONS list

# Skip outside a git checkout (a tau-compiled spec's emitted project has none).
# A container build without .git supplies the same three values as env vars.
if(EXISTS "${CMAKE_CURRENT_SOURCE_DIR}/.git")
execute_process(
	COMMAND git describe --tags --always
	WORKING_DIRECTORY ${CMAKE_CURRENT_SOURCE_DIR}
	OUTPUT_VARIABLE TAU_GIT_DESCRIBED
	OUTPUT_STRIP_TRAILING_WHITESPACE
)
execute_process(
	COMMAND git rev-parse --abbrev-ref HEAD
	WORKING_DIRECTORY ${CMAKE_CURRENT_SOURCE_DIR}
	OUTPUT_VARIABLE TAU_GIT_BRANCH
	OUTPUT_STRIP_TRAILING_WHITESPACE
)
execute_process(
	COMMAND git log -1 --format=%h
	WORKING_DIRECTORY ${CMAKE_CURRENT_SOURCE_DIR}
	OUTPUT_VARIABLE TAU_GIT_COMMIT_HASH
	OUTPUT_STRIP_TRAILING_WHITESPACE
)
else()
	set(TAU_GIT_DESCRIBED "$ENV{TAU_GIT_DESCRIBED}")
	set(TAU_GIT_BRANCH "$ENV{TAU_GIT_BRANCH}")
	set(TAU_GIT_COMMIT_HASH "$ENV{TAU_GIT_COMMIT_HASH}")
endif()

set(TAU_GIT_DEFINITIONS
	"TAU_GIT_DESCRIBED=\"${TAU_GIT_DESCRIBED}\""
	"TAU_GIT_COMMIT_HASH=\"${TAU_GIT_COMMIT_HASH}\""
	"TAU_GIT_BRANCH=\"${TAU_GIT_BRANCH}\""
)
