# populates TAU_GIT_DESCRIBED, TAU_GIT_BRANCH and TAU_GIT_COMMIT_HASH variables
# and creates TAU_GIT_DEFINITIONS list

execute_process(
	COMMAND git describe --tags --always
	WORKING_DIRECTORY ${CMAKE_CURRENT_SOURCE_DIR}
	OUTPUT_VARIABLE TAU_GIT_DESCRIBED
	OUTPUT_STRIP_TRAILING_WHITESPACE
)
execute_process(
	COMMAND git rev-parse --abbrev-ref HEAD
	WORKING_DIRECTORY ${CMAKE_CURRENT_SOURCE_DIR}
	OUTPUT_VARIABLE TAU_GIT_BRANCH
	OUTPUT_STRIP_TRAILING_WHITESPACE
)
execute_process(
	COMMAND git log -1 --format=%h
	WORKING_DIRECTORY ${CMAKE_CURRENT_SOURCE_DIR}
	OUTPUT_VARIABLE TAU_GIT_COMMIT_HASH
	OUTPUT_STRIP_TRAILING_WHITESPACE
)

set(TAU_GIT_DEFINITIONS
	"TAU_GIT_DESCRIBED=\"${TAU_GIT_DESCRIBED}\""
	"TAU_GIT_COMMIT_HASH=\"${TAU_GIT_COMMIT_HASH}\""
	"TAU_GIT_BRANCH=\"${TAU_GIT_BRANCH}\""
)
