if(NOT CCACHE_BINARY)
	find_program(CCACHE_BINARY ccache)
endif()
if(CCACHE_BINARY)
	set(CMAKE_C_COMPILER_LAUNCHER   "${CCACHE_BINARY}" CACHE STRING "C compiler launcher (ccache)")
	set(CMAKE_CXX_COMPILER_LAUNCHER "${CCACHE_BINARY}" CACHE STRING "C++ compiler launcher (ccache)")
	message(STATUS "Using ccache: ${CCACHE_BINARY}")
else()
	message(WARNING "ccache not found")
endif()
