name: Release Packages

on:
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4

      - name: Build image with release packages
        run: docker build --build-arg RELEASE="yes" -t packages .

      - name: Copy release packages from container
        run: |
          CID=$(docker create packages)
          docker cp $CID:/tau-lang/build-Release/packages ${{ github.workspace }}/
          docker rm $CID

      - name: Read Version
        id: version
        run: echo "version=v$(cat VERSION)" >> $GITHUB_ENV

      - name: Upload release packages
        uses: actions/upload-artifact@v4
        with:
          name: "release-${{ env.version }}"
          path: ${{ github.workspace }}/packages/

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: "v${{ env.version }}"
          name: "Tau Language Framework Alpha ${{ env.version }}"
          body: "Tau Language Framework"
          draft: false
          prerelease: true
          files: ${{ github.workspace }}/packages/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}