name: Release Packages

on:
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4

      - name: Build image with release packages
        run: docker build --build-arg RELEASE="yes" -t packages .

      - name: Copy release packages from container
        run: |
          CID=$(docker create packages)
          docker cp $CID:/tau-lang/build-Release/packages ${{ github.workspace }}/
          docker rm $CID

      - name: List release packages
        working-directory: ${{ github.workspace }}/packages
        run: echo "Listing release packages" && ls -la tau-*

# TODO add upload of release packages and creating a release