name: Test Debug

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test-debug:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - name: Build debug tests and run them
        run: docker build --build-arg TESTS="yes" --build-arg BUILD_TYPE="Debug" -t debug-tester .
