name: Test Release

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test-release:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - name: Build release tests and run them
        run: docker build --build-arg TESTS="yes" --build-arg BUILD_TYPE="Release" -t release-tester .
